apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "agrofort.fullname" . }}-secrets
  labels:
    {{- include "agrofort.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "agrofort.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
      remoteRef:
        key: secret/agrofort
        property: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
    - secretKey: RECAPTCHA_SECRET_KEY
      remoteRef:
        key: secret/agrofort
        property: RECAPTCHA_SECRET_KEY
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: secret/agrofort
        property: RESEND_API_KEY
    - secretKey: EMAIL_FROM
      remoteRef:
        key: secret/agrofort
        property: EMAIL_FROM
    - secretKey: EMAIL_TO
      remoteRef:
        key: secret/agrofort
        property: EMAIL_TO
