apiVersion: v1
kind: Secret
metadata:
  name: ghost-secret
type: Opaque
data:
  admin-email: "{{ .Values.secrets.ghost.adminEmail | b64enc }}"
  admin-password: "{{ .Values.secrets.ghost.adminPassword | b64enc }}"
