apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: "{{ .Values.secrets.mysql.rootPassword | b64enc }}"
  database: "{{ .Values.secrets.mysql.database | b64enc }}"
  user: "{{ .Values.secrets.mysql.user | b64enc }}"
  password: "{{ .Values.secrets.mysql.password | b64enc }}"
