{{- if .Values.vault.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-secrets.serviceAccountName" . }}-vault
  namespace: {{ .Values.vault.namespace }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault
{{- end }}