{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore | default "cluster-secret-store" }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: secret/data/{{ .Values.externalSecrets.remoteRefs.accessKeyId }}
        property: key
    - secretKey: secretAccessKey
      remoteRef:
        key: secret/data/{{ .Values.externalSecrets.remoteRefs.secretAccessKey }}
        property: key
---
{{- if .Values.longhorn.ui.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore | default "cluster-secret-store" }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: longhorn-auth
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: secret/data/{{ .Values.externalSecrets.remoteRefs.uiAuth }}
        property: auth
{{- end }}
{{- end }}