apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "longhorn.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn.labels" . | nindent 4 }}
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: "1.5.3"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      backupTarget: {{ .Values.longhorn.backup.target }}
      backupTargetCredentialSecret: longhorn-backup-secret
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/lib/longhorn
      replicaAutoBalance: best-effort
      storageMinimalAvailablePercentage: 15
      upgradeChecker: false
      defaultReplicaCount: {{ .Values.longhorn.replicas }}
      defaultDataLocality: best-effort
      defaultLonghornStaticStorageClass: longhorn-static
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      volumeAttachmentRecoveryPolicy: wait
      snapshotDataIntegrity: fast-check
      backupstorePollInterval: 120
      taintToleration: "node-role.kubernetes.io/storage:NoSchedule"
      systemManagedComponentsNodeSelector: "node-role.kubernetes.io/storage:true"
      priorityClass: system-node-critical
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      engineReplicaTimeout: 8
      supportBundleFailedHistoryLimit: 1
      backupConcurrentLimit: 2
      restoreConcurrentLimit: 2
    
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultMkfsParams: ""
      defaultClassReplicaCount: {{ .Values.longhorn.replicas }}
      defaultDataLocality: best-effort
      reclaimPolicy: Delete
      migratable: false
      recurringJobSelector:
        enable: true
        jobList:
          - name: "daily-snapshot"
            task: "snapshot"
            cron: "0 2 * * *"
            retain: 7
            concurrency: 2
            labels:
              job/snapshot: daily
          - name: "weekly-snapshot"
            task: "snapshot"
            cron: "0 3 * * 0"
            retain: 4
            concurrency: 2
            labels:
              job/snapshot: weekly
          - name: "daily-backup"
            task: "backup"
            cron: "0 4 * * *"
            retain: 7
            concurrency: 1
            labels:
              job/backup: daily
          - name: "weekly-backup"
            task: "backup"
            cron: "0 5 * * 0"
            retain: 4
            concurrency: 1
            labels:
              job/backup: weekly
    
    csi:
      attacherReplicaCount: 3
      provisionerReplicaCount: 3
      resizerReplicaCount: 3
      snapshotterReplicaCount: 3
    
    ingress:
      enabled: {{ .Values.longhorn.ui.enabled }}
      ingressClassName: {{ .Values.longhorn.ui.ingressClassName }}
      host: {{ .Values.longhorn.ui.host }}
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        cert-manager.io/cluster-issuer: {{ .Values.longhorn.ui.clusterIssuer }}
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: longhorn-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Longhorn UI'
    
    longhornManager:
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Equal
        value: "true"
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/storage: "true"
    
    longhornDriver:
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Equal
        value: "true"
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/storage: "true"
    
    longhornUI:
      replicas: 2
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Equal
        value: "true"
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/storage: "true"