{{- if .Values.longhorn.ui.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.longhorn.ui.ingressClassName | default "traefik" }}
    
    # Basic authentication
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-longhorn-auth@kubernetescrd
    
    {{- if .Values.longhorn.ui.tls.enabled }}
    # HTTPS configuration
    cert-manager.io/cluster-issuer: {{ .Values.longhorn.ui.clusterIssuer | default "letsencrypt" }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}
    
    {{- if .Values.longhorn.ui.security.ipWhitelist.enabled }}
    # IP Whitelist
    traefik.ingress.kubernetes.io/whitelist-source-range: {{ .Values.longhorn.ui.security.ipWhitelist.sourceRange | quote }}
    {{- end }}
    
    {{- if .Values.longhorn.ui.security.headers.enabled }}
    # Security headers
    traefik.ingress.kubernetes.io/headers-strict-transport-security: {{ .Values.longhorn.ui.security.headers.stsSeconds | quote }}
    traefik.ingress.kubernetes.io/headers-strict-transport-security-include-subdomains: {{ .Values.longhorn.ui.security.headers.stsIncludeSubdomains | quote }}
    traefik.ingress.kubernetes.io/headers-strict-transport-security-preload: {{ .Values.longhorn.ui.security.headers.stsPreload | quote }}
    traefik.ingress.kubernetes.io/headers-x-frame-options: {{ .Values.longhorn.ui.security.headers.frameOptions | quote }}
    traefik.ingress.kubernetes.io/headers-x-content-type-options: {{ .Values.longhorn.ui.security.headers.contentTypeOptions | quote }}
    traefik.ingress.kubernetes.io/headers-referrer-policy: {{ .Values.longhorn.ui.security.headers.referrerPolicy | quote }}
    traefik.ingress.kubernetes.io/headers-browser-xss-filter: {{ .Values.longhorn.ui.security.headers.browserXssFilter | quote }}
    {{- end }}
    
    {{- with .Values.longhorn.ui.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.longhorn.ui.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.longhorn.ui.host }}
    secretName: longhorn-tls
  {{- end }}
  rules:
  - host: {{ .Values.longhorn.ui.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
{{- end }}