apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    adminUser:
      create: false
      username: admin
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
