# =============================================================================
# GHOST BLOG HELM CHART CONFIGURATION
# =============================================================================

# -----------------------------------------------------------------------------
# Chart Configuration
# -----------------------------------------------------------------------------
nameOverride: ""
fullnameOverride: ""

# -----------------------------------------------------------------------------
# Infrastructure Configuration
# -----------------------------------------------------------------------------
namespace: "vausiim"
releaseName: "vausiim"
host: "vausiim.ee"
replicaCount: 1

# -----------------------------------------------------------------------------
# Application Configuration
# -----------------------------------------------------------------------------
image:
  repository: ghost
  tag: "5"
  pullPolicy: IfNotPresent

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------
database:
  host: mysql.mysql.svc.cluster.local
  user: "vausiim"
  database: "vausiim"
  # Password managed by External Secrets when externalSecrets.enabled=true
  # Set this only for development/testing when externalSecrets.enabled=false
  password: ""

# -----------------------------------------------------------------------------
# Storage Configuration
# -----------------------------------------------------------------------------
pvc:
  size: 5Gi
  storageClassName: ""  # Use cluster default
  accessMode: ReadWriteOnce

# -----------------------------------------------------------------------------
# Service Configuration
# -----------------------------------------------------------------------------
service:
  name: ghost
  port: 80
  targetPort: 2368

# -----------------------------------------------------------------------------
# Ingress Configuration
# -----------------------------------------------------------------------------
ingress:
  enabled: true
  className: "traefik"
  host: "{{ .Values.host }}"
  tls:
    enabled: true
    secretName: "{{ .Values.releaseName }}-tls"
  annotations: {}

# -----------------------------------------------------------------------------
# Mail Configuration
# -----------------------------------------------------------------------------
mail:
  enabled: true
  transport: SMTP
  from: "noreply@vausiim.ee"
  options:
    service: Mailgun
    host: "smtp.eu.mailgun.org"
    port: 587
    secure: false
    auth:
      user: "postmaster@mg.vausiim.ee"
      # Password managed by External Secrets when externalSecrets.enabled=true
      # Set this only for development/testing when externalSecrets.enabled=false
      pass: ""

# -----------------------------------------------------------------------------
# Security Configuration
# -----------------------------------------------------------------------------
# External Secrets Configuration
externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStore: cluster-secret-store
  secretStoreKind: ClusterSecretStore
  remoteRefs:
    dbPassword: wauhost/ghost/db-password
    mailPassword: wauhost/ghost/mail-password

# Security Context
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # Ghost needs write access
  capabilities:
    drop:
      - ALL

# Pod Security Context
podSecurityContext:
  enabled: true
  fsGroup: 1000

# Network Policy Configuration
networkPolicy:
  enabled: false
  # When enabled, allows traffic from:
  # - Same namespace
  # - Ingress controllers
  # - MySQL namespace
  ingress:
    allowSameNamespace: true
    allowIngressController: true
    customRules: []
  egress:
    allowDNS: true
    allowMySQL: true
    allowMail: true
    customRules: []

# -----------------------------------------------------------------------------
# Performance & Reliability Configuration
# -----------------------------------------------------------------------------
# Resource Configuration
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Pod Configuration
podAnnotations: {}
podLabels: {}

# Node Selection
nodeSelector: {}
tolerations: []
affinity: {}

# Health Checks
livenessProbe:
  enabled: true
  httpGet:
    path: /ghost/api/v4/admin/site/
    port: 2368
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /ghost/api/v4/admin/site/
    port: 2368
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# -----------------------------------------------------------------------------
# Ghost Application Configuration
# -----------------------------------------------------------------------------
ghost:
  # Production configuration
  config:
    # Ghost behavior
    privacy:
      useUpdateCheck: false
      useGravatar: false
      useRpcPing: false
    
    # Performance settings
    database:
      pool:
        min: 2
        max: 10
      acquireConnectionTimeout: 60000
    
    # Paths configuration
    paths:
      contentPath: /var/lib/ghost/content
    
    # Server configuration
    server:
      port: 2368
      host: "0.0.0.0"
    
    # Logging configuration
    logging:
      level: info
      transports:
        - console

# -----------------------------------------------------------------------------
# Multi-Environment Support
# -----------------------------------------------------------------------------
# Environment-specific overrides
environments:
  production:
    replicaCount: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    ghost:
      config:
        logging:
          level: warn
  
  staging:
    replicaCount: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  
  development:
    replicaCount: 1
    externalSecrets:
      enabled: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
