apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../secrets/mysql.yaml
  - ../../../secrets/vausiim.yaml
  - ../../../secrets/agrofort.yaml
  - ../../../secrets/kraman.yaml
  - ../../../secrets/onebetwonder.yaml
  - ../../../secrets/tahetrukk.yaml
  - ../../../secrets/waushop.yaml
