replicaCount: 1

deploymentAnnotations: {}

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: ghcr.io/waushop/kraman
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull-secret
nameOverride: "web"
fullnameOverride: "web"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: kraman.ee
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kraman-tls
      hosts:
        - kraman.ee

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

env:
  NODE_ENV: production
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: 6Leaq4EsAAAAAA6uoSLyroLkG56ZHE1W8HHWrFve
  DB_HOST: mysql.mysql.svc.cluster.local
  DB_PORT: "3306"
  DB_NAME: kraman
  STORAGE_ENDPOINT: hel1.your-objectstorage.com
  STORAGE_PORT: "443"
  STORAGE_USE_SSL: "true"
  STORAGE_BUCKET: kraman
