apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "raha.fullname" . }}-data
  labels:
    {{- include "raha.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
