externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStore: cluster-secret-store
  secretStoreKind: ClusterSecretStore
  remoteRefs:
    rootUser: wauhost/minio/root-user
    rootPassword: wauhost/minio/root-password
    backupAccessKey: wauhost/minio/backup-access-key
    backupSecretKey: wauhost/minio/backup-secret-key

namespace: minio

minio:
  image: quay.io/minio/minio
  tag: RELEASE.2024-01-16T16-07-38Z
  
  # Credentials managed by External Secrets
  # Set these only for development/testing when externalSecrets.enabled=false
  rootUser: "admin"  # Override with external secret
  rootPassword: "mustikakissell"   # Override with external secret
  
  storageClass: local-path
  storageSize: 5Gi
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  
  api:
    host: images.waushop.ee
    ingressClassName: traefik
    clusterIssuer: letsencrypt
  
  console:
    host: minio.waushop.ee
    ingressClassName: traefik
    clusterIssuer: letsencrypt
  
  buckets:
    - name: agrofort
      public: true
      lifecycle:
        expiryDays: 7
  
  backup:
    enabled: true
    schedule: "0 3 * * *"
    endpoint: "https://s3.eu-central-003.backblazeb2.com"
    # Credentials managed by External Secrets
    # Set these only for development/testing when externalSecrets.enabled=false
    accessKey: ""  # Override with external secret
    secretKey: ""  # Override with external secret
    prefix: "minio-backup"
    buckets:
      - agrofort-products
      - agrofort-news
      - agrofort-uploads

rbac:
  create: true

podSecurityPolicy:
  enabled: false

networkPolicy:
  enabled: true
  allowedNamespaces:
    - default
    - wordpress
    - ghost

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

podAnnotations: {}

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  labels:
    prometheus: kube-prometheus
  metricRelabelings: []