apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  releaseName: cert-manager-issuer
  targetNamespace: cert-manager
  interval: 30m
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: ./infra/cert-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    externalSecrets:
      enabled: false
