---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:RELEASE.2024-01-16T16-06-34Z
        command: ["/bin/sh", "/scripts/create-buckets.sh"]
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "minio.fullname" . }}-credentials
              key: rootUser
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "minio.fullname" . }}-credentials
              key: rootPassword
        - name: HOME
          value: "/tmp"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: scripts
        configMap:
          name: {{ .Release.Name }}-config
          defaultMode: 0755
      - name: tmp
        emptyDir: {}