{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  rootUser: {{ .Values.minio.rootUser | required "minio.rootUser is required when externalSecrets.enabled=false" }}
  rootPassword: {{ .Values.minio.rootPassword | required "minio.rootPassword is required when externalSecrets.enabled=false" }}
{{- end }}