# Storage Monitoring Configuration

# Chart configuration
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

monitoring:
  namespace: monitoring
  
  # MinIO monitoring settings
  minio:
    totalStorage: 100  # Total storage in GB for alert calculations
    endpoints:
      - minio.minio-system.svc.cluster.local:9000
  
  # Longhorn monitoring settings
  longhorn:
    namespace: longhorn-system
    serviceMonitor:
      enabled: true
  
  # Alert settings
  alerts:
    enabled: true
    # Alert thresholds
    storage:
      warningPercent: 80
      criticalPercent: 95
    backup:
      maxAge: 86400  # 24 hours in seconds
    performance:
      maxLatency: 1  # seconds
      maxErrorRate: 5  # errors per second

# Prometheus configuration
prometheus:
  retention: 30d
  storageSize: 50Gi
  ingress:
    enabled: false
    host: prometheus.example.com
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt

# Grafana configuration  
grafana:
  adminPassword: ""  # Use external secret
  persistence:
    enabled: true
    size: 10Gi
  ingress:
    enabled: false
    host: grafana.example.com
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  
  # Dashboard provisioning
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'storage'
          orgId: 1
          folder: 'Storage'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/storage

# AlertManager configuration
alertmanager:
  enabled: true
  persistence:
    size: 5Gi
  
  config:
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
        - match:
            severity: critical
          receiver: critical-receiver
          continue: true
        - match:
            component: backup
          receiver: backup-receiver
    
    receivers:
      - name: 'default'
        # Configure your default receiver
        
      - name: 'critical-receiver'
        # Configure critical alerts receiver
        
      - name: 'backup-receiver'
        # Configure backup alerts receiver

# ServiceMonitor labels
serviceMonitorSelector:
  matchLabels:
    prometheus: kube-prometheus

# External Secrets
externalSecrets:
  enabled: true
  secretStore: cluster-secret-store
  remoteRefs:
    grafanaAdminPassword: wauhost/monitoring/grafana-admin-password