# ======================================================================
# Longhorn Helm Chart Values - Single Node Optimized
# ======================================================================
# This file contains values for your wrapper chart and the Longhorn subchart
# Values under 'longhorn-app' will be passed to the official Longhorn chart

# ======================================================================
# EXTERNAL SECRETS CONFIGURATION (Custom Extension)
# ======================================================================
# Note: This section is for your custom chart wrapper - not used by official Longhorn chart
externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStore: cluster-secret-store
  secretStoreKind: ClusterSecretStore
  remoteRefs:
    backupAccessKey: wauhost/longhorn/backup-access-key
    backupSecretKey: wauhost/longhorn/backup-secret-key
    uiAuth: wauhost/longhorn/ui-auth

# ======================================================================
# LONGHORN CORE SETTINGS (Official Chart Compatible)
# ======================================================================

# Default settings optimized for single node - MOST IMPORTANT SECTION
defaultSettings:
  # Core single-node settings
  defaultReplicaCount: 1
  defaultMinNumberOfBackingImageCopies: 1
  
  # Disable anti-affinity rules (not needed on single node)
  replicaSoftAntiAffinity: false
  replicaZoneSoftAntiAffinity: false
  
  # Storage optimization for single node
  storageReservedPercentageForDefaultDisk: 10  # Reduced from 30%
  storageMinimalAvailablePercentage: 15        # Reduced from 25%
  
  # Backup configuration
  backupTarget: "s3://longhorn-backups@eu-central/"
  backupTargetCredentialSecret: "longhorn-backup-secret"
  
  # Performance optimizations for single node
  autoSalvage: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  engineReplicaTimeout: 8
  backupConcurrentLimit: 1  # Reduced for single node
  restoreConcurrentLimit: 1  # Reduced for single node
  
  # Additional single-node optimizations
  createDefaultDiskLabeledNodes: true
  defaultDataPath: "/var/lib/longhorn/"
  upgradeChecker: false
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  snapshotDataIntegrity: "fast-check"
  backupstorePollInterval: 120

# ======================================================================
# CSI CONTROLLER SETTINGS - CRITICAL FOR SINGLE NODE
# ======================================================================
# CSI Controller replica counts - REDUCE FROM DEFAULT 3 TO 1
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

# ======================================================================
# UI CONFIGURATION
# ======================================================================
# UI configuration
longhornUI:
  replicas: 1  # Reduce from default 2 to 1

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: "traefik"
  host: longhorn.waushop.ee
  tls: true  # Enable HTTPS
  annotations:
    # HTTPS configuration
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
    
    # Force HTTPS redirect
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    
    # IP Whitelist configuration - Replace with your allowed IPs
    traefik.ingress.kubernetes.io/whitelist-source-range: "88.196.115.202/32"
    
    # Security headers
    traefik.ingress.kubernetes.io/headers-strict-transport-security: "max-age=63072000"
    traefik.ingress.kubernetes.io/headers-strict-transport-security-include-subdomains: "true"
    traefik.ingress.kubernetes.io/headers-strict-transport-security-preload: "true"
    traefik.ingress.kubernetes.io/headers-x-frame-options: "SAMEORIGIN"
    traefik.ingress.kubernetes.io/headers-x-content-type-options: "nosniff"
    traefik.ingress.kubernetes.io/headers-referrer-policy: "strict-origin-when-cross-origin"
    traefik.ingress.kubernetes.io/headers-browser-xss-filter: "true"

# ======================================================================
# STORAGE CONFIGURATION
# ======================================================================
# Persistence configuration
persistence:
  defaultClass: false  # Keep longhorn-single-replica as default
  defaultFsType: ext4
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete

# ======================================================================
# RESOURCE LIMITS - OPTIMIZED FOR SINGLE NODE
# ======================================================================
# Resource limits optimized for single node
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# ======================================================================
# NETWORKING & SECURITY
# ======================================================================
# Network policies disabled for single node simplicity
networkPolicies:
  enabled: false

# Priority class for critical workloads
priorityClass:
  enabled: true
  name: "longhorn-critical"
  value: 1000

# ======================================================================
# NODE CONFIGURATION - SINGLE NODE OPTIMIZED
# ======================================================================
# Tolerations and node selectors - empty for single node
longhornManager:
  tolerations: []
  nodeSelector: {}

longhornDriver:
  tolerations: []
  nodeSelector: {}

# Service configuration
service:
  ui:
    type: ClusterIP
  manager:
    type: ClusterIP

# ======================================================================
# MONITORING & OBSERVABILITY
# ======================================================================
# Enable monitoring
metrics:
  serviceMonitor:
    enabled: false  # Set to true if you have Prometheus operator

# ======================================================================
# IMAGES - USING OFFICIAL LONGHORN IMAGES
# ======================================================================
# Image settings (using defaults, but explicit for reference)
image:
  longhorn:
    engine:
      repository: longhornio/longhorn-engine
      tag: v1.8.1
    manager:
      repository: longhornio/longhorn-manager
      tag: v1.8.1
    ui:
      repository: longhornio/longhorn-ui
      tag: v1.8.1
    instanceManager:
      repository: longhornio/longhorn-instance-manager
      tag: v1.8.1

# ======================================================================
# CUSTOM CHART EXTENSIONS (For Your Wrapper Chart)
# ======================================================================
# These sections are preserved for your custom chart functionality
# They won't affect the official Longhorn chart but provide configuration
# for your external secrets and storage class management

# Namespace configuration (custom extension)
namespace: longhorn-system

# Longhorn wrapper configuration (custom extension)
longhorn:
  replicas: 1
  backup:
    target: "s3://longhorn-backups@eu-central/"
    accessKeyId: ""  # Override with external secret
    secretAccessKey: ""  # Override with external secret
    endpoint: "https://s3.eu-central-003.backblazeb2.com"
    region: "eu-central"
  ui:
    enabled: true
    host: "longhorn.waushop.ee"  # Replace it with your actual domain
    ingressClassName: "traefik"
    clusterIssuer: "letsencrypt"
    tls:
      enabled: true
    auth:
      username: ""    # REQUIRED: Set admin username when externalSecrets.enabled=false
      password: ""    # REQUIRED: Set admin password when externalSecrets.enabled=false
      htpasswd: ""    # REQUIRED: Set htpasswd string when externalSecrets.enabled=false
    
    # Security configuration
    security:
      # IP Whitelist configuration
      ipWhitelist:
        enabled: true
        # IMPORTANT: Replace with your actual allowed IP addresses/ranges
        # Examples: "192.168.1.0/24,10.0.0.0/8,203.0.113.10/32"
        sourceRange: "88.196.115.202/32"
      
      # Security headers
      headers:
        enabled: true
        stsSeconds: "63072000"  # 2 years
        stsIncludeSubdomains: "true"
        stsPreload: "true"
        frameOptions: "SAMEORIGIN"
        contentTypeOptions: "nosniff"
        referrerPolicy: "strict-origin-when-cross-origin"
        browserXssFilter: "true"
      
      # Rate limiting (optional)
      rateLimit:
        enabled: false
        average: 10
        burst: 20
        period: "1m"
        ipDepth: 1
    
    # Additional custom annotations
    annotations: {}

# Storage Classes configuration (custom extension)
storageClasses:
  singleReplica:
    enabled: true
    name: "longhorn-single-replica"
    isDefault: true
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
      fromBackup: ""
      fsType: "ext4"
  backup:
    enabled: true
    name: "longhorn-backup"
    isDefault: false
    reclaimPolicy: Retain
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
      fsType: "ext4"
  standard:
    enabled: false
  fast:
    enabled: false

# Network Policy Configuration (custom extension)
networkPolicy:
  enabled: false

# Single node annotations for identification (custom extension)
annotations:
  "longhorn.io/single-node": "true"
  "longhorn.io/deployment-type": "single-node-optimized"

# ======================================================================
# DEPLOYMENT NOTES
# ======================================================================
# This values file is designed to work with both:
# 1. Official Longhorn Helm chart (longhorn/longhorn)
# 2. Your custom Longhorn wrapper chart
# 
# For official chart deployment:
#   helm upgrade longhorn longhorn/longhorn -n longhorn -f values.yaml
# 
# For custom chart deployment:
#   helm upgrade longhorn ./charts/longhorn -n longhorn -f values.yaml
# 
# Key optimizations for single-node:
# - All replica counts set to 1
# - CSI controllers scaled to 1 each
# - Anti-affinity disabled
# - Storage reservations reduced
# - Resource limits optimized
# ======================================================================

# ======================================================================
# LONGHORN SUBCHART VALUES
# ======================================================================
# These values are passed to the official Longhorn Helm chart
longhorn-app:
  # Default settings from the HelmRelease
  defaultSettings:
    backupTarget: "s3://longhorn-backups@eu-central/"
    backupTargetCredentialSecret: longhorn-backup-secret
    createDefaultDiskLabeledNodes: true
    defaultDataPath: /var/lib/longhorn
    replicaAutoBalance: best-effort
    storageMinimalAvailablePercentage: 15
    upgradeChecker: false
    defaultReplicaCount: 1
    defaultDataLocality: best-effort
    defaultLonghornStaticStorageClass: longhorn-static
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    volumeAttachmentRecoveryPolicy: wait
    snapshotDataIntegrity: fast-check
    backupstorePollInterval: 120
    priorityClass: system-node-critical
    autoSalvage: true
    autoDeletePodWhenVolumeDetachedUnexpectedly: true
    engineReplicaTimeout: 8
    supportBundleFailedHistoryLimit: 1
    backupConcurrentLimit: 2
    restoreConcurrentLimit: 2
    
  persistence:
    defaultClass: true
    defaultFsType: ext4
    defaultMkfsParams: ""
    defaultClassReplicaCount: 1
    defaultDataLocality: best-effort
    reclaimPolicy: Delete
    migratable: false
    recurringJobSelector:
      enable: true
      jobList:
        - name: "daily-snapshot"
          task: "snapshot"
          cron: "0 2 * * *"
          retain: 7
          concurrency: 2
          labels:
            job/snapshot: daily
        - name: "weekly-snapshot"
          task: "snapshot"
          cron: "0 3 * * 0"
          retain: 4
          concurrency: 2
          labels:
            job/snapshot: weekly
        - name: "daily-backup"
          task: "backup"
          cron: "0 4 * * *"
          retain: 7
          concurrency: 1
          labels:
            job/backup: daily
        - name: "weekly-backup"
          task: "backup"
          cron: "0 5 * * 0"
          retain: 4
          concurrency: 1
          labels:
            job/backup: weekly
    
  csi:
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1
    snapshotterReplicaCount: 1
    
  ingress:
    enabled: false  # Disabled - using our custom ingress with security features
      
  longhornManager:
    tolerations: []
    nodeSelector: {}
    
  longhornDriver:
    tolerations: []
    nodeSelector: {}
    
  longhornUI:
    replicas: 1
    tolerations: []
    nodeSelector: {}