{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cert-manager.fullname" . }}-email
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore | default "cluster-secret-store" }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ include "cert-manager.fullname" . }}-email-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        email: "{{ `{{ .email }}` }}"
  data:
    - secretKey: email
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.email }}
{{- end }}