apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: "{{ .Values.certManager.email }}"
    server: "{{ .Values.certManager.acmeServer }}"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: "{{ .Values.certManager.ingressClass }}"