---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager.clusterIssuerName" . }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  acme:
    {{- if .Values.externalSecrets.enabled }}
    # When using external secrets, the email will be injected from the secret
    email: {{ .Values.certManager.email | default "admin@example.com" | quote }}
    {{- else }}
    email: {{ .Values.certManager.email | quote }}
    {{- end }}
    server: {{ .Values.certManager.acmeServer | quote }}
    privateKeySecretRef:
      name: {{ include "cert-manager.clusterIssuerName" . }}-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.certManager.ingressClass | quote }}
