apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-tls
spec:
  secretName: wordpress-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.wordpress.ingress.host }}
