apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Values.wordpress.env.WORDPRESS_DB_HOST }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.wordpress.env.WORDPRESS_DB_USER }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.wordpress.env.WORDPRESS_DB_PASSWORD }}"
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.wordpress.env.WORDPRESS_DB_NAME }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
          resources:
            requests:
              cpu: "250m"      # 0.25 CPU (enough for handling normal requests)
              memory: "512Mi"  # 512MB RAM (to handle caching and basic plugins)
            limits:
              cpu: "1"         # Limit WordPress to 1 full CPU core
              memory: "1Gi"    # 1GB max RAM (adjust if needed for heavy plugins)
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc