{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.env.WORDPRESS_DB_PASSWORD | required "wordpress.env.WORDPRESS_DB_PASSWORD is required when externalSecrets.enabled=false" }}
{{- end }}