{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | required "auth.rootPassword is required when externalSecrets.enabled=false" | b64enc }}
  {{- range .Values.databases }}
  mysql-password-{{ .name }}: {{ .password | required (printf "password is required for database %s when externalSecrets.enabled=false" .name) | b64enc }}
  {{- end }}
{{- end }}