apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: "{{ .Values.mysql.rootPassword | b64enc }}"
  database: "{{ .Values.mysql.database.name | b64enc }}"
  user: "{{ .Values.mysql.database.user | b64enc }}"
  password: "{{ .Values.mysql.database.password | b64enc }}"