---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3306