apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}
    spec:
      containers:
        - name: ghost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: url
              value: "https://{{ .Values.host }}"
            - name: database__connection__host
              value: "{{ .Values.database.host }}"
            - name: database__connection__user
              value: "{{ .Values.database.user }}"
            - name: database__connection__password
              value: "{{ .Values.database.password }}"
            - name: database__connection__database
              value: "{{ .Values.database.database }}"
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: {{ .Values.releaseName }}-pvc
