apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:latest
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "{{ .Values.ghost.database.host }}"
            - name: database__connection__user
              value: "{{ .Values.ghost.database.user }}"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: url
              value: "https://{{ .Values.ghost.domain }}"
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-storage
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-storage
          persistentVolumeClaim:
            claimName: ghost-pvc
