apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vausiim-ingress
  namespace: vausiim
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "vausiim.ee"
      secretName: "vausiim-tls"
  rules:
    - host: "vausiim.ee"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost
                port:
                  number: 80