{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ghost.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    {{- if .Values.networkPolicy.ingress.allowSameNamespace }}
    # Allow traffic from same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
    {{- end }}
    
    {{- if .Values.networkPolicy.ingress.allowIngressController }}
    # Allow traffic from ingress controllers
    - from:
        - namespaceSelector:
            matchLabels:
              name: traefik
        - namespaceSelector:
            matchLabels:
              name: nginx-ingress
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
    {{- end }}
    
    {{- with .Values.networkPolicy.ingress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  
  egress:
    {{- if .Values.networkPolicy.egress.allowDNS }}
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    
    {{- if .Values.networkPolicy.egress.allowMySQL }}
    # Allow MySQL database access
    - to:
        - namespaceSelector:
            matchLabels:
              name: mysql
      ports:
        - protocol: TCP
          port: 3306
    {{- end }}
    
    {{- if .Values.networkPolicy.egress.allowMail }}
    # Allow SMTP mail access
    - to: []
      ports:
        - protocol: TCP
          port: 587
        - protocol: TCP
          port: 465
        - protocol: TCP
          port: 25
    {{- end }}
    
    {{- with .Values.networkPolicy.egress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
