---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ghost.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 2368 }}
