apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.releaseName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 2368