apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kraman.fullname" . }}-secrets
  labels:
    {{- include "kraman.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "kraman.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: secret/kraman
        property: SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: secret/kraman
        property: SMTP_PORT
    - secretKey: SMTP_USER
      remoteRef:
        key: secret/kraman
        property: SMTP_USER
    - secretKey: SMTP_PASS
      remoteRef:
        key: secret/kraman
        property: SMTP_PASS
    - secretKey: EMAIL_FROM
      remoteRef:
        key: secret/kraman
        property: EMAIL_FROM
    - secretKey: EMAIL_TO
      remoteRef:
        key: secret/kraman
        property: EMAIL_TO
    - secretKey: RECAPTCHA_SECRET_KEY
      remoteRef:
        key: secret/kraman
        property: RECAPTCHA_SECRET_KEY
