apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kraman.fullname" . }}-secrets
  labels:
    {{- include "kraman.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "kraman.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: secret/kraman
        property: SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: secret/kraman
        property: SMTP_PORT
    - secretKey: SMTP_USER
      remoteRef:
        key: secret/kraman
        property: SMTP_USER
    - secretKey: SMTP_PASS
      remoteRef:
        key: secret/kraman
        property: SMTP_PASS
    - secretKey: EMAIL_FROM
      remoteRef:
        key: secret/kraman
        property: EMAIL_FROM
    - secretKey: EMAIL_TO
      remoteRef:
        key: secret/kraman
        property: EMAIL_TO
    - secretKey: RECAPTCHA_SECRET_KEY
      remoteRef:
        key: secret/kraman
        property: RECAPTCHA_SECRET_KEY
    - secretKey: DB_HOST
      remoteRef:
        key: secret/kraman
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: secret/kraman
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: secret/kraman
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/kraman
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: secret/kraman
        property: DB_NAME
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/kraman
        property: JWT_SECRET
    - secretKey: STORAGE_ENDPOINT
      remoteRef:
        key: secret/kraman
        property: STORAGE_ENDPOINT
    - secretKey: STORAGE_PORT
      remoteRef:
        key: secret/kraman
        property: STORAGE_PORT
    - secretKey: STORAGE_USE_SSL
      remoteRef:
        key: secret/kraman
        property: STORAGE_USE_SSL
    - secretKey: STORAGE_ACCESS_KEY
      remoteRef:
        key: secret/kraman
        property: STORAGE_ACCESS_KEY
    - secretKey: STORAGE_SECRET_KEY
      remoteRef:
        key: secret/kraman
        property: STORAGE_SECRET_KEY
    - secretKey: STORAGE_BUCKET
      remoteRef:
        key: secret/kraman
        property: STORAGE_BUCKET
