name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: debian-latest
    needs: review
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Deploy Ghost
        run: helm upgrade --install ghost ./charts/ghost

      - name: Deploy MySQL
        run: helm upgrade --install mysql ./charts/mysql

      - name: Deploy Ingress
        run: helm upgrade --install ingress ./charts/ingress
