---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: ferryscanner
spec:
  encryptedData:
    .dockerconfigjson: AgDVZBzQWNekG0aylEJSsdU8P6noRSnD1BzJfpy+uWFtCJfkeZHsL9mDStH9hNzeOSLBCrUo6fQFsDVWX470fQ+GRKdObhtbZH8PYB6idEPSpeQ/YqM7yT6dYmXD1IDO6Za4KYyH9viiLzICYOics/7SL07hUMHmey6BUfVVnK+dWqk2z69x7+vs2aK0g1uNAoEXb9RGiPTwB+mnNcc3jR6Mlh21P+KiG6NysRvpDDLYTeh3u309H+zzT46JyrSb+sXJuwk9GfyopE2iIy0rpOVgu1Fh+IKWADAmxcG5TYA/AjI0Kfhd4d/pe9rsz6TIkxvJ+nb3o8LFonl/T6u7weRPRobVnd7vihEDYq6ARAAVqQhGpSak12ColkANJBCo7YaGBK1os+zMMtg9yPWQ7bPOK4U+vldChL07QueLb/6/RwXDmmrPUqsc9eMXPlM6lUqH+YurSosecZV/ZJz7KHhts1jP5zQW6Pu0yoURjOU9ERAwihgsSbQbPuKYBpVgyzpLx6YqIW4c5Hyc/G2abyxWW8RMhCUoqwiHpWC9xb0d+IMWo17wP1IfgQEIGBhQjUW3TCmI1rwl4tiRlRWj+4UZjhvLbGdvjsVeoVj55YRTSk0vQcLM1KkqPTpa5S4c9BHDxmfydPn1DrPfWCIxkY0DqqIUSz2PwEi/ZFBm4xFQCj4MWwTAj+lsDhUiKi4sLEQ/SKcbAHcJZ/O5a8Y1MWUN4/wSSVo/q9NsQXJEVycJ5HS60KvrtBNEB7gx/djLoVjuepJGMda8iYwCBrAUJJDt/ar7PqMZ7IbgRzSNO26aXWxCnxpIZz5nsalReBPPzrTXHrh/ruMPK4iufGcnF+FU83bZf2IwXXygXXsAkdEHBmTcbnjCQkCAP+OG76CA1FzRCLbG1npKkJBTMznSzLGHNS32xt3+sq4QPtP9
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: ferryscanner
    type: kubernetes.io/dockerconfigjson
