---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: mysql
spec:
  encryptedData:
    mysql-root-password: AgBJM/Zbay91nvZ3b9x9S0gN2QpVhryzrzvu0NmroC5/9vqoxvbXIVssxTohaBT7TlSYnNaplx4/Z2wqkVwjnAU2+R54wYGtCI2fDMPL1HouJgz17bT/O9wtibBqfJfk+qOwryq07PULnfUtLXj66aeTOGkORS/79eW3G7rs43PnuUjIF4EHq5QhQ6rGTDAOj7I4B3d/vfphe91LXuOq40iq34DOHayJXAlW7MNYrF7K1BaxcGz8In8XFey1e5no8U5fLyYCeQ6++3Lf+z65TAhqJijrCONJc/1L47F0tlyJEx6pjW1b/upjrccZ7DsYRChxUEnh1AXTZWelL6ulqrKCrpo0yjFMBgfuanDHkHuRevh+UgJu81pLoPtgDbSS9UmPacvA1iJsfME0iQfXHeyUJc5gjh2McOw1yrTx38VkeE2uDAL3HtRW+b36CIx/KQbW8JayLOTBFXgj9I2u7sC9L1CelTXqpQlVPrk+u27qmhlFNHKccUDc5HK0TtrlyvRx4m+pc7VR+0bnSEBOlM2woDRy1/h4kPMKx5JW3wUnwUytsQ9ffqUyBaDuFUIBdWenbsld9oY9Cli4QCWWB74Ck/mbR2b/slB0RVHWWM51ow91lqUpnXG+63ZjFMCnRL1PvVKA+tZ5XLNCKG0lijdGzMNbUGfEMjOmiPKRrsnSs0v5TxSTG/zLo9Hry5qW7YfPfVgnOF7hAB4mX/7sgH+nIYzlFBJe9S9k2Vp9WtIaqN33CQc=
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: mysql
        meta.helm.sh/release-namespace: mysql
      labels:
        app.kubernetes.io/managed-by: Helm
      name: mysql-secret
      namespace: mysql
    type: Opaque
