---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: raha
spec:
  encryptedData:
    .dockerconfigjson: AgBJbJyB+dbdW7O2n2//9rYJBTQ3Kp53fjnUjNCnOEwaZ8fB5mYya7KSBPsDa/TlPoMErjVcphL9UkRCSJs/jzvqGY+8rdBvonfUjw3zDYYRYXoZst3mutbjLEZfXWb4wKXBaH3FBP/mvDlcqKFJV1v1BwHAIW3P4nEGMWABZl8HGx4T2cnW/28P22R4EZDWFGOtM89gKN8TL2FJAiSMJmqTkJPRbBzYw4kZYqLOAvUsl2HHMKrRhidOTg8QodbiDkeAau2vmZ0HTjyY7IJTbpk9Xh+3lWpjLPV8l+GIAmeIE8Kqp4J1Zidj7NwOyIvTUhTMZJyEnby6nl5hDGzleiK09MRuHKKMKEj1EaWI+mIhpmI2r2aYsUZDG3LZyGB9lzbbcP0WEX1hA4tt/T6czl63eban4wZJiFqJNXXumlNc2iqrPyuouBtGNH4lo4CYBETw5FHpLNfU5uIdfQ4tYEfcChnilA+oa2S2gP0Dj/bj2LSnK6lANRukCndANDlhv0+wSAM7y0MI4vYzTyP/C4ihvjWaHhc85DMMFRQBP2tZyG6gIUnCEyXjFKoD9J6VoFTyQBUTYDqYGhefF3IHn3GPR30c2JITNYx91daipuORjoD3tz348uf7IYafXr9F6KYtUCCKg3XkiRdCyHJ4nGFvgntSR0KPBpTJ7DxWsat/k91g9pAJfIVR7GBQ2t905ZPmhbgag1I8V1H+wojOcDcP46dw9YvgJ3biexy/PI4r6b9ymP/Ueot+NkqosfR8MHK9AdA6VJW4uvvvhgjWhbtMafHzQ3ZhXli7aO36AVWuuHKeLXuPg51LNgNkif3PSM/PHST0AYWE1iaYJJzkoub3c72ZGPXJiSlxWUmcsLIb6g5te5Jp8sVls607f5siom0rnHTOEUibBDltztzlxnwgRZ77UG8eprHbpqeO
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: raha
    type: kubernetes.io/dockerconfigjson
