---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: tahetrukk
spec:
  encryptedData:
    .dockerconfigjson: AgB8/kC5FivryBeUUHMCplozYFgehwwuRenScgtblrFI3ozgceArWWt7wLozD94FU7/Lx2e9ZunD0kFJk1zf+hoWF0S9RYuVDwuZMalIBVxEadeaE6qsbo6zS1mX8x2TIqzbx/Sx7i+p4xIUl38b01GMV3AYk6nMdZonQGNjz55E+zzz3Z45gnz1dII8U80I2elwtyFA0lx0wvBXOWYYlKcDdgNWE9gk0+pvmH0UCB2d74m2N4Ej72edcGLaQruuzo7uOR+So5y841/sXBxwcVkQMGw5jcueiyHYC1nlQtLgoFKpVz+fYIuyGYsqqqoG1hbCxvrtgp18WzGEWER8ZyIfbihIMfXx6EFv4xtj30c08zLilyb+xrb0JG8rq6bvj0EpAV2FCx8APwybQsSmyfdwcRvZfDpxI/1fW6MwLRqram/h+RjXXpQY14p0zZ5qKMLf8X62J8qE8I4aoVtTx0fY9qRQ84aksASmMq0Y5jiLmG+kEjaep3ZXWkw6VriMd8vGSKB9yIXTd8uzLJSfjAbd9c0q+LhcecGV16vPQB3BYQxNqa+Qp2AC2jQWHm3wXb5cL6+rXpnf6MQ6wI0SxxKC20vjzlAjyzpVnw8VJl/tNl4w1wZjXhYzODAMmkf1+sqBuKGqbIxAkvlDqakNkyQtFrUX3Gn/jAH3fdZKZCQCvj/O3UZDfv5y40C/rk8DNLvKPcbPNfDOPGREj7UaHxDyeYoT5tpwWUYJrSgZWlByUCZkzB8E/Gqy9/S8bj2K//MBMXZCGmDlIJNRHfY9sBUMOc0yWRcpvj1HQ2tXDrnTtE3EzD/21i7K7Iy3HnzckYTmjGv+UzbmFbnMif0jiV4k73qD1Kt32PW9W8iW5kQcoFKW+S8JM3RWETQlJGefYEaAf+zxByqNnRG08EQZXGBfm/gASr7l+rnEnX0DwIzv8Vv9F3RO788m3wty5X8rvQ6VdL9igdHUKBUpHifB+JWTyNzpR+oo+w==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: tahetrukk
    type: kubernetes.io/dockerconfigjson
