---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: tahetrukk
spec:
  encryptedData:
    .dockerconfigjson: AgBUlv/IQnt/BsGwZJ45AWm2Cm0JnOjLjeQgQrEvAuhbm9O5rpxQQppWfGvgt4gerNIt1yO/xSFCDFCKQnyE4fKC0UHgXi8lHCuFUbx+CmuQ6P/gREh5Zq1PI7S2xw+b5NQwbR2o5g4ikKQnM1te2+XomBDYDLn7Z8hAGSyZMa9FmAMg7OWIT5NXOsSiTaLW0/cJnDR3slDpOSbkc4a0Zf8+gGiFPsEsiWJCgxlyblAsoThIJnZwaMU6m+h6ld5Uxj5LnFJCYaCeh2yzR/I5OkAlwLpojbZ9a/0bvuKHLK9a4M4MIJHh33IGfVqxcHOTF45K4byrM0/2YOjLyT/dLrVHQxLL2esFjwXBHYaw47Aig4v1+T6EgjC+7o9Ty0FFoSfWTOPuJ9uVP3bqkeMFkW7UzGrx7WIePFz+c77epV9Hed50M8U4fcFbrKjvQ4UeNo3QFFTnhtWveHB/Qv5zOQYQ5KvxB+q51t1uBwIdw5lb0GgPKsSzejwYS7xVrl8vrjg2nwCsr4F2lXTU9b88/xSgPmaSOcaWVpdCKNpskth7pipwm8oSuBYxOMP+A5EgsRDrHlHNaORQi5+sF2Qrheal6C2U9aGinEk4evLPBAQyy0dC1Rk3iKkZjksOGYCWKx43Rl7F0bIldE2ogHP4hdOxxKDLm41L5OvEAK8bk2jnlbZhzzkUTxWKmMrEdENnCS8OupVfmOFVmbNZmRJ0qFblvOY+OoFzQMvtXbhqHay7F7iNFCHTPJH1d/ih0kLdfgN6C7hZlu4nUocraIkvHnmj1MlRhRc7enfr5FlpquODhZQ1DaGRzGW3awJ46+wurg28hVVG0nfcd09cpF4Bm83nSin+34lCk6yHOX7Lr8ZQgB6+ftj8+0XhdDoNfJdtZQIRC6pnNYL2Wm2+itnn5Y/rZkdiaqnVYp3Kkxp9
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: tahetrukk
    type: kubernetes.io/dockerconfigjson
