---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: tahetrukk
spec:
  encryptedData:
    .dockerconfigjson: AgBQVqBAWeecf5UpshGRbZ2MNEDEnWSZDY5+lG+SEVtMlEVOpWn6roczUU1RiC/Ru/NYhJmdQ+KqVYxi8XQsjcOkmtfDGxvjiJZBM6f3kSSgvPeMWLHp/u5VeZOTjLbkkk3TMi8pRysOqqcc7b6XBQ2FP2HuiMxhYrE9axBqTt3Fu7rLu4ErGTnc3xukakohVqwhnYFt3WSQLsDrIOJLXM07QhXG0MM79X1ruO06I815dJD1sI95MlgukVXuccBsgOiwuS474GClc8PzC+sTubpYa0if2AQgH7dKPj3439O2fctv2P114duKa4J3rdYwZ6HhuHM1/kcLurS0ln9rP470d8HfDpaJBFORys7qJReK7ARo7kV2fm6GmwF9GifFkEzrsQ77O1txRChfnbaFFck9/P4J1+2yfppUw/p4iDYqA3GfWqeevly/66mmQozlAar1tAmJv3B+oFRYpGhJ4HFrdo52V8esEAcv33T/Wc+MVyWdceSnxNsL6GY0WMgEaQjlSFI2qtnLEQlUbka46hPxja42tpvShZ0hBAqZjtk6CW5ifGb+iT8IQ7Ion7tkxvcxsTWEvBXh1mBML75yMBR3TOgT96se/hHbX/JSGyu+pXOvOiF604lp+BJJ9F6YmCs6HHF638v/pW7JIwywdrfEg2Gx14T+q2X0hqkvIZKq2OH+IaBY6/fbFY/gqMsJQsIKvQgByc3kNDkUzcNjMdV3Uv8ytRoM4KVLLnGvCk1Ggth45B6gHYvAfLw21vtAB+32RRFux/5ADSVXr+OJNYm6JJNyRx5ywveKIXubdl7XzmEW8X/av/FiHaTH5DpsOVc/o/Ler5piP2gYFg6wIf926o+Azq0YVEZmxRzRa36DhUgBaVUF56OQ4gggiqSV5j9QFo8jxRwzgLPznEEui7oMPtTBy78NANQE/L2yRjJ/WCorr+wCjxMaz2tOqEgT7akLjVBqw+/j1jFmd6TS99h7dSxK5v2TLQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: tahetrukk
    type: kubernetes.io/dockerconfigjson
