---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-secrets
  namespace: vausiim
spec:
  encryptedData:
    database__connection__password: AgASMJzYzrIGHMsDgex8Pik87ucImrdwBiD4bcLRMM9JGwCviuZPrphbD08NKxPHU+4B22rTIbwn7zDQQIrV5IW9dDJvRieTsCo0FNcd6ZcvN7pnoX5CRRaYkK5e6IE1wGvHyEA6C2DNKZ3KvI9+DluUJBrtWI/Eb1MGBwIH3mYijD1DS6baWA9ywZ1lgi84lvsqxkJXYN9piltl0Q47CGrnICc30tlymWqOJc5uwIIh7pi6Z0fHnF0qwCwYoFagNihOXcHvaeNHsXyI63Byap0Rm3g/eaMobZqnJPhDabzFpnASZdtY0kxC5ni5zzRttY5mQPD4mZsNlo+4UqdnxCvk9v67MWcewD4OaDz48+WtetZW7NLAWO8mYSmmcN2pv+5z9HiSdr42EBWjHRVZY5NQmhquHJ6TCrFR89skV5Pi18zIF6SeLSch2bCUowbgQBmZMBvQYdrKkeuL2jgH1KVH2NE4HPFG870L5WLqz0mDJTpKfqNYGZxdYhrY9sbH06JuJ5VPzEEOMRMl4em0rNPlYseEAayrnunGdCb7Jf12jKBefkklQ1n6bfG46lzCEasFvSeiHIXfBDXfXVIr8v2RQjMBDgUL44xaN2SIs1OjJZyTtfCOJTchXvkFPAZVyNtXN3oLMBiMaHDuxxCv29JswiSkDwwHydAyH7oCZ/MIxFTPN8NHq8N6msxef2qKmPTYt/wqPuL9kN1iY5bukTg6DfjG2rtKRvABaQU7Bzg=
    mail__options__auth__pass: AgAOZsQV7LicSEjq6wD0HaernaajOpUYV6l7hmA/Oyn/NPv4y/iGd8xCgCAX5Y+BZklLzxY5QowN7JN02rfh3u5r9QC2T6dej9BiL3ACel0JX0r/M81KP78RmNEWG60qpvoyffpQq/FdRwyIXckmPfORAMdWDwHctDs0m0uLTWp0U2dzQA1Ahf695DgtrgdpfuyShDkK7r6Syz8Bkal22V5HnnzNN1i79dYWH82WlVgAsKihH8lS5mAKKudQUNRKOQCfHN+5GSd88h5l9yqYa0gCLXKd9Uqx9LDaoZKb1SV0L+nK918cheYW/BX/6GtYkPHlTIuH6G26PAdVVLtY0agH2nOHWO58kxwpdiXPUchAPawrOVmIdvPEe8eFswGmrecVLaraOd+krkwb7ZqR4As0+1GlD9LtDmRvumgSkQI1wCzc+W8wvVxTbq42NZeN32/7FmjOOh8wfTT89MsU+bgyoa1/bLpdtryKqn+za9mjSqONIs18UwI4eeZlGpoekgnM901OhKjK9ZrswHFXrc4KrqGdaeDOwA4tc8VTufvkoVKKU56Ia463sG/BUoAhNN6/5rOnizlUADRl8gYXT7sBT1rui30R3C+IReuMMxfgVImncqXaVhFFziqvc6yB3CUBczGlH6wrSGnnHAn7JCh0jdmOYq9bHkAgXOFJ1Vywwge7Yt35uXXJEBqK7dMZCEG9JUUqqS/f2kJv9bUhbiuUahUAjICeFtOGvSd1sVftMg==
  template:
    metadata:
      name: ghost-secrets
      namespace: vausiim
    type: Opaque
