---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vausiim-ghost-secrets
  namespace: vausiim
spec:
  encryptedData:
    database__connection__password: AgAZz+OZZg0IvSLqwjV1JVUL5/w5WsQt7Xj/C7zwtn3zGQ/8Welj33sqUmuZRkTjN4gV1X6siLJ2x/26bZf2+wMIBJRUOLPhO2pjklyjaAOy96dURyHVDOl8OdkpnLyTX+rWaNdUpJvUyWI1fByACuA0weFXUp+DbnqRxJYUB8JTYa5Y4vtOlenQB5bfpYsALHDEqbrnLKXwWTP0FwTENFufr7qtvua++y3h1XGYhQIbWSvDZiVrm+RybGArUtRmj5n6OMBEExP9O0MhgiZnnqwQoE1B7ZoCeN7xmdhOcayxgB9SrlFXK1lkhJ0cN+88iMbd77JWYqG6Sw182PFME7Rt84liZcgakkjBThkSZmqL3l5NkY8WXP7dwSGICO/8E693OH3DLHzTM+MMTcTITqSCoXyybyZLGo7zNlzinIswMMggs6+5fqpbyN3vc4zgkCUxgYVf20JQERRu4gXvQDeJUg97TW+EfrguLMGRsQteEcsX8RE1apraL/kU9tVv7dAmupNohdhX5XJnznR3dIf3KHPozAhcPSv84QEQlWPDIDIkvsOGSSkm9H6xmZQ+fKrjtLyQRFqNx1Jd48pulE1kqd2CyD19ZgZj7chJu8wYpY6Aq7vW7bTXpDHWEAXHp9EfE+W1q9GFzlogmBb6q7pRst64rbHBwnnnGqPDkYY9Y3q+7ogQSOwhkKxtOSkdCH6S7kmtQkbbdsfjjzVwg7SNKvyor127WhnOIdLCvR0=
    mail__options__auth__pass: AgCGSPsgERW3Y9M5E1abrTwS0I2pFdyM0KiOkEeu5/0aTcQoM/ffUyhEttniUAp9mUBbE4CTY7BIr3S6yoLiZFj8xioAh1DB+082/RzGuWwQYM5AwJ7Han4k1HA9mcqbgrRD/RtLGCDiH6j7UAvlAHJg92VFa78JlfL7KkFXCzD1owdp9BDF60awAKGZvHiYNQKzdHpoDcU+Z9k/4uMERHgSd0QI7a3IGPRedrdofiG2AQ96B8OqP1DieyD+pSDvvSnQl5brtnbB/r+dmiw8zsI9ZlKHPn/zOpyyncMa0eymnXeR2h0w/7WHiJtscciCY5v/Wh+VekjpWilXeBWqkuktBq931IztQ5ETY4kzZMqqgjrzg6sph9KSaRsH2UD3Bo2R5upLD8AkPqAnJoyRJtXNrmLLbSt6o39ebD/zIeHimh/jknKJMdy5KYeFBAOocLGpSxj1R5JA3jQ5Hl7SBD28FKJvTzG3VaG5ZgqwULkc2B0/y0kNap/5cKzFv6nEgiYXR4jy9MCI+TXEpvECao3Bvw8IMqiYRtE1bu+qBy2A6ScKLmC9eiUPaSjadHsRgjjYSm0/+lU1JLOud7zhDp8lGnEmDban3k3K+iUCODq2Es2MHMiCmV4ycMdMUbhOz7J1DR2OfZHc6HOfASUZspk4tt6c1SXqfQ5KueMKH2Vb2PV9j8mNhLFiNsEQgJ5BLbUSaYqgIE9cAwPoQkp2TuQ+ILSBgu8VaR57rZ6wUvsfBQ==
  template:
    metadata:
      annotations:
        reconcile.external-secrets.io/data-hash: 7154c414101dfa2f82419adeb43ef8fc06520acd86b14e8c093e6bfc
      labels:
        reconcile.external-secrets.io/created-by: e5bd96c49f0f60cc30a7e0beb93f1e5c6a15d23975266e0bfc6fb6ea
        reconcile.external-secrets.io/managed: "true"
      name: vausiim-ghost-secrets
      namespace: vausiim
    type: Opaque
