---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wauhive-master-secret
  namespace: wauhive
spec:
  encryptedData:
    master.secret: AgCTqV1xJN2lIAQ6qDu3jKW4dcvz5zTGjC2yiv4qXbsBXAzGAHH5WjwBiwHp+XzaZaol9VpfYcZOKwamkUFclByEU5SnHW+jbsyvCXKL1SDM1Lr3kyDCJxRpG64y0i7MVEX+A+VL67Ckiu9F1JUaep82On1sFbo5Xdl+qsk/8jkGj5XQyaOgsgjAYkv+fTlAlCN841MMFy9SlcziILetLoSJE8Adqax0aY37rjQDirYEJETJJWAesX56xVIcFn+x1XyK02G7ct4FaVKNqdIpitVEX3arbEDEzQjTCO3UFZKX4RvPX6Gn943yZv97k/jMfh4QB1XVuu85YzZLnxMWyEu56BwHIqcQafizeFUMtmiHjue/VpFLdjb8lPTtcB0WPjCk8UUIC61wcVC2H+9h87kxae99qvoYaqjrjMyhNvbgbdSo+qUyQ2fyjqBCw5vhG2iMNM7RXUWGcYTnlYFmm2WzvIBUz4HMfK5xZNIf3lcNiU1W8Qw90Ogz0QSwOeTsOtIcJMJaYl5iuiZnamBadgTu++SGdJYjcWq3ZVL5ZzgxRJWJJPQubg4xDsDG7aP66VZrYLXr/wQDssMtQWsTP+VXBbJjt/AabbXFnAbuq46eTvko17Kts2qU+zEg09J8Xwo7Q/+2Xy2/UUyEpBMoZyZMICXzaic98J5LMzItFFe/2WKlhGihzBjJJzeHvZqZndWgHw0CZ4xckLRXNV1lAzr32TLFMHd2gN0p/288EHC9uQ==
  template:
    metadata:
      name: wauhive-master-secret
      namespace: wauhive
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wauhive-secrets
  namespace: wauhive
spec:
  encryptedData:
    LITESTREAM_ACCESS_KEY_ID: AgACzv8JK1It4aykSh3p6WdaAMbJsWfJN3MLUkcoSK/33suRzlWoLrqPT7SQnku23NyQI7inQHx+VrS9+uiGX75MOpkrW8fCcF0R6eSax/Bjo6hsOyH9E9CyFIvT6bIjvMpid+hLSkYfGsdFUVEw+cz2GHApzlG+GR6bHcbGRZRaAxiTuD6gTPMNIfTTn5AAdvc/illowXUl0I6Mb0eznM6Sj6txB4gnwCnqRD9sH6GlDo4T3JsgnOLr974HLVjwlU3p4mGP/PbJb8ln5g41GoFT21sZNNcfTy4PMeS6+77KIcx011w8cyb//Z3oTqPPPwjb4fYiug7mXTpuDbGK0S1YF3O0I1kInEKRCvdAZ6wptPzSmH1kppWofc/JxctBZWT7Z7agV6PVnqA0P4JEg4oG2379HgNJ7x/dKueaFgE1guiGNy45wOmquenUb6uFYPrXuVRyVDsgGrspUmodQaMEXD5/qtIjnIzLT4rI878r8x0f+B7NwlqAJifO7vS5dHOMeRTzQJkvqnctEbpMNI5fHHlrDYWwLCOTG+Att0lEd4nLOyDskQIJIo6RuODSaYQr2JTj+nsGesGoHtkmGjjjxL/9ikK5rjcqkEiBVMyPzDXnwV/vBhmxy9FtK8sYQ86otPUzZ5iZPNXTPYc+8KrJXBFSI8tCj6oluez8j2YKVsoNnkzT4YCkD8XDFTbRk6bibbU2e/8+YYqA1ivBnPRI5b7V6g==
    LITESTREAM_SECRET_ACCESS_KEY: AgAWyoi3Rrd6v1acLQTGl79Y2FAJp1oeCLlj0Ytw0xuLRDAkR+ZQpqavsXWpDQKT9TPbDgeEYtIJGOQfJkiX8OHQic6SG0KSzd3Cpji3NBA7tCPvlaSoLPMOcS0htuunUaqi+JvqJfSrsZs983R4QH/cuKzu3cF71XMRaeF+Kt849+cBI9m2HILbZ/Wh7w1Y/HvWyqBxyOhnAXumDMyje8GmlIqI0B6lV+HcZXXN2cjiqNQ3uib9+/o+Y6ELNlaUGRPcNoWkteUC8nmQTKhfJQQRr11wuj8yZa+sZgw90xffpvSlE1hR4ShTKpdPvCfhaUNjncKD77rpLbWD8KqkRjvFOB/C5g4tCsoDWwTE34IJbTLl2sy+OsCoK+ytRuQSMeFVcjykPz0XYtYLlUGnAVVY4s2sGHFQuihWvfpMRlIGirNZTsxpjv+Tm3bldkUVS5P6AnYXocMnpY5Baf/Eso0MPqmOkKNt099vyZk16Qm1p3eZ9Gs3J0svydwZCQkMJYM1JaVs9PD26ZvcAZVmqr/kSWn/yG+iJqDYMIcSwQkc4HFsF/XfCDGXnANRAnbKYfDwgwqKm4FgrsbDhCRMfZS4tQWK++uxm7vtMP0YLTqivSgqrp7oY4rlOoLIJTfMll5W2l2DPgXaIqK9Tn2if7WHwlyNzWc+ecp2qwrGhkNyDeJ1KaJf133o7QYQI+aSASfy6V+Qa1hyN56CXmzZsVNVyQAnYc9z/gGwt67zr377TR1IPWuzpR8i
    WAUHIVE_PASSWORD: AgAVzW+AeHzFhTblEOn3cWtGjcDTuo+YLO0BZnbXbODVZ8gKv/SFOT7LR7XeuLPhAr6dL/lLeuxVmaT4Dfjuu2UH52bOozS7CvasjwVzwJu2jB/Ir7kOWzPRH17Ua5Jc7s1or3l52WPayL6pfUSNa06R/85ycyUHOzpEeDuW/k5IUQhTYFpGsm6sbGA0DHCs3OPnoJsqArMwdqZYGOTiRizRACCHBsISq2OOL1w4SuONtt31rXDi2i6XNAL/esRznJPA5ShWKIoLP2onxB6gha5QCe9TVG5gORKfokXc+V/ilgtvf0DLMGfyIMSpYzraimI8oPFG0INJ/v76DWh24LzLBFRP5PJhmWcoGxD4PsePhBpS/TduY/rNvTEtPxevGfHz4jSeX9egS+J77o1qzcv4CfRkHsQyaNSidrB2NuqSqNy4zxtKOxbwqqU1lBQqlbU3okfKnHBXQBQGAKSxgPdpFknbFNQO5M+fNqUMQMBPSQTfrOj3nZZCuEAYU92nFW83PlfNCn6bcunwPxn5SISW4HWQDaRONjgwwzw/tj/WHFTk3DvuFSxnZIYM3YmfwSKbLfkBezvBbk5smmI0laycj2Lx33UX/KQ3OjVtqLSfH0/juOqRS1jQ1o1IT7yabMKNs6Rg8foybrIz0f5mFlgy9SZtHX7j4+Ioi1MgYk94bWLJ8u0EauLv2hzLk9Q29DeZa9aOa16jkfOK1biGaTOG5ZwlXFT0SyvG8+7UzhOD6IlzjQ8=
  template:
    metadata:
      name: wauhive-secrets
      namespace: wauhive
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: wauhive
spec:
  encryptedData:
    .dockerconfigjson: AgBnJ891gf1XXuFRFCv2faag7WOun/L4PpPUF1hmOtJ5vh3JKFXYqL9XgV+Ud3ik1sGDGvdtQW1U83RtKKg5FWQ3dGWdooSCeJUV5V2WoWR2KqMQat1UW3Dp2vHD+qoqSYDuqptVePq2Ifx4dqT52UaT9AgpS8D+/dlvvCZu1n7x0Pzykk4NG5OXtyX+X9TmHDtct5qvLh8JrkZtolooJGLrOWQ8MbUCVaW+y/8poLszffuCRXP5CvoLDl+Ncbu2k7nR8PDAvxiTnqCIKvlLD8owOhDM7wSpcQPyaeWGpC8BAmbgnfEF/BvuOcKWot8l3Cb755J4Y/BCSZoRmkBF22piSR40GRJK2i8oVmzZHr3Qj0Fe7+00tD5WehM7KHXY0xm45uqq1pLTlnnTyIjQ0K9XH/v+bqWqNxkA9QWa9cvth3lGCZqu4PhjVW8MI9a4kXRQBFsFazzMFQIZTfI7OEvLNYObigIiF9g/EfhBSTxIWsCV2wxTiiKhqVqkpsaxxC+UVRTIUdA5oKWtuCDtJJ1xrluSHPTGtRvX6Qz6MU6kzVm/9SmONlKIGI2FiPgSmzoA0R7G2tE6slPCU7W/cqdrT4wf77aGf0KI2u/p3j0OFCbfL75kuqAKkdaIn9a7P+bCSKxotJr9pKesJ5wJthfHShoFwTeyUbUxwArghMjqXJ3Fq/iL6mQ0J2OOCbV49OAU+lxfTWjrog9cLmqf6JoTN9HmHfRIslaB9sQ/UXn64dq3ZdL/CeKgRAwG3VqRoQB7/eSvOMdxAcL/wGH7UVng7dnPQn/zmoCn7pYrNqt2ATskIRQQTggCarpyIi8uqCK0qCUQYznuab9L1yazPWkfbNg6coyr8A36mQNLwtjXCBsq+Y9Lohna8tZY6LaWSZDlOCuTAtYtvtvPMPTVneFWNhSfuNzkfn6GvBJ9
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: wauhive
    type: kubernetes.io/dockerconfigjson
