---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: waushop
spec:
  encryptedData:
    .dockerconfigjson: AgCc+G77fSqE3AL3XLKOE56j/KJEJp2dScdaGv+Q2tPXg3IwR09cHn9dQZuNae0E31dzShFJgb5Q60z0wqwV1oHQQ+2xrBd5e45WJYlW2Ss2RUYu+y9d8sqgggRgddzcf/Tg1MnTBkHLHQnB7qKMw+xyC2ZEWIETq3aau3KpyJ2abJkg4hU8fXT3aSt8Mcx525/qQEzV9i/UotbSapBKFDQ2f60gl7DpfOsR6uHxkndAX82xKt5ZQ5KtYdW0aINWx5FBXJlLPRjraYR94MbnMQSJIz5enRUvAHYHnEppbKzii2NlAL41RW0n504n5MOeP1OvjRxke0KTO+7/efYoxwkGCxU61nRXckh+fiKa/qMbHbdnrLeehrVNDJ2SThfuyMbEQQh2lEOx4ojaYpC9aXXR+DuFsRTu3cuWGarXQl4HSU3sx4nf1s0b1bLYYVuwfKvDFmKqocANUXguH0fLWRt/jLPrAzgrAzTVO8dPnlGyZJg1om1U4L0lFTDnzt5OIQHQvneDmM/GZ3f0DNERWnwj1I1k0CUE5bdnVt5r9pl1HM8zlUcurLkfxMB6+Rj8iVlhEA0+cR8TD1kqkNCUHu3ND91YgF0hkbYloH4mBvFP2iAoiTMtaVwtxyPuUV9xzumCbO0rPiBmDcT1oZjwv1bPMr2e9SVw9lDXuIOOquFg6PN53mUkM0lQxKCkSA0+akz5FRnz2ik15oXR+s81OpcnFrxNF8myQtsmpaugEAABuPbt8C9tIrKjwkCkAbaTb804Y8uweEMz5wa/JXs724SVGt5IN6UV5LlcZ05YBLvMQa0DXekaL2DmnO2EZoyrAMT2NPdbxMQATEFhUanLoT5vjldAcAR1OKjfzs++pTWBemG1fFBj4TiVeOHESoy38JamwUG5Yx4fA0+zdsBUtpVhImm5LRKUZ27mcbBv
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: waushop
    type: kubernetes.io/dockerconfigjson
