---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: waushop
spec:
  encryptedData:
    .dockerconfigjson: AgAvx2DlO7uOThfMXQEK7pXAISB+vxVUJsWZYeCie1z0kmkFAXl9WOMv2h/lkoIHebGXu2bPXt7EO33lwudaGBCrCqya6Vcb2pNxlozd7MBO9BhJI43WJuQYVM1HuRSfxGXqzuSGHnbX5yzgkvLQvwUek9ZdSzeRnNT5BTBPVCZyWWXKZs8CbiQ99l4faGq36WSFkOAB6Ck7O+OQq5RAyMgFyPPPNGc+QWkY3gSq1x+4OLmViiDcoDbQCWdrhoQKmO215OIAm0ZyuOYQvRr9UM8DL1Dm/gYOyUMIXogJBF4T0Qrr488k4VENTqPEpq3ZYxUTroFr/bKpGp9E0N6UmhgdJIZc+s2d6No030uAlBPkIR3NlBDx1It/TfqePDzliE0lzIMtPAbKkoSfRf929xvxq2sysZ8wY0JO/y9pSgMQ6zysQwiVxnqbnjrHF0mRhtQQ3SDoyc5fV6/22uVQPz1Yv1e5b7sxyjUDqxabSey59nn+tr8Bz43JXR2CnTTpi2jjYvfjCe/Gs8N6H3Ox3/Yio1wSFJ7kMWEnaXmgeABcrtPHQg1bxlSzrBsjsohH9XLOpS+EkdO075Et7nPt3hlXdSXidT8lTObVWKQleLA0kwTXpGEeBG7/8+eyFUr+nHLnJHjalBcj8s2cVPB8Rz2lPbGb+01S7VMX1r6imSEXGtPNL1zvs1RqLhkklGDarUWbRP4GSNQpDABd+zjapZWnWu2z63i3qgSFM5wI4FnfCxc8V6D81nEpi+eCUz/Mr2zZQ+n0nOqCdS34jtBxytZQ0EiuKR41gn6KQN/FH1r0pOYwg01M11I5Gf0PafYuWsInAZPM57S/lVQ3HPbeveHD+DEJxMwYMo8GgjP+yFgiz2Hx3JbA0JtI4MQLkK7DSZoAAGJ0uNVoEuB1uQ1y44kXLzogXEBwAdloczWS+gJxqkZ0lgFDbxrjxnVPvLZ++zP4SH7E2M/ZZvvv8py18qvtVJisH98RSg==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: waushop
    type: kubernetes.io/dockerconfigjson
