---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgCGLGhP75z0oYn2N47KdkDeUaZxPq/pOcQ9L+2KlNyqaMBEw26TEYhW4nTmWAgOC7tcWViwRG2P1CzxFQXdvkarjk9cat+rOnD0PlWUZp5+mIrRN9K3U5EL2Ndmug/XXGCJQ61MM/vDo/+mp7n0a1beiwTsobEN722SJXDXgtZ38+Vn3OJHrG7TQT9hnI26+JGslBoFmfRaHjaldKolJvX8pVwEOAFYBNd7VMNNg7t+1LURbXWgI7LlJqY6tVW0+wBMyNeBtqNPjyDvPNICNOZX8Hk5LNDQXi4P8CEEZPuw93Dd++vSYLQE167xN0V89nqExIU1UmSevQKWHQDktG+R8EdaacGbDKOdkG71FY8gz94kvhin+8zTeRekcWw6kMJnEbdazn8wuhgr27nA8xX5iEIa9Hvd7580wsh6YnC7tIXhC6csIHSBNxMx3uDWMgAjZBr7XR53lsNgmZ+gA9rD2ZDlgLJOJYrPv+gXmjGX0/gdCCMy4c+n+iRyd/woRr13MkimZ7OiqS9egGZlPy5Dhevf4ELGoIiwqJXdYFgPDiTadRcdW8LdB1lraFNgkU2JaikPuCOHXD2Okb11fKlD14z8EeF2vEfUvEM4O9QA3r1OzNgriQ1ONAu3s2GhbbJ5NOj6VaPj5PS5/TWKOyDsiIlT6v0ww+EdJSnaUaVUJMq15bw8Nq/CLxMwZ+2Bz73Cq0EwkZSg0jaYgfWbp75ticytIx3UNa6Ju+ej3c8xpeSnkpzNGVU8bJBbOREou0aPUVhKjpuCsDbSb40=
    username: AgAL+SCKTzK02BGYHuOZSp71Vdo9FO9FmRx7CM1x33vbE+xMApA7lgqkyQKWwlDsrUuxesTwlwZynosMA04zrLJ25rEA4mKZOInW12Za2NLs2IDS7XJmh+YMA5Q5Ni+SXvSS3UGLNOiRaYrDnPEclPUi/DRGisBx/CHNNwvQeSArMBzSuId4Cns1syUs2jwS/urA2gk7/q/dS97frJJKDJNzBKdfHOSdo1i9jdSFSwN2Gf0JFsHVYVYYsJ/dsGrbbkb/QJcWCEcHvl1fa+tundNNb6GWucO0VAvJH3alMIUxReptQVlKdzEViHybWL0z/vvLvP0ftteRcpDTFJ214toT79OEVNdYRUA/cMaGZeLJvkubPpKo15/u6Lbqam1QHV1XmM93s7Jfd6E6G4IGWcf1NfXl8EWu9AJkMqx7uZv6nygxkRsj++0F7dr+b+rmIlUPd20pFIUGgVrxq8M+TcDOAhcp76gdcGO1weZ91UGGU8qaiT6Adj46JN+z62AbMQafNO3+F9Y14OfKqU2nbmUwup3taCuv7tvtuFXYluYHJsdBNQ98uMgKBPutKmDO6mzcd8hp5A6ZFa9hUA2o1jVqwKFU/+YrulB1gkSUVeEGLgaxcdSOfCzrf2zOLRABFvAHXaNqhj7D2kVgCc5poHDiPbvxFTdQttdAri1jlSgyXSnu9F2tecAoiVzbTC+z47eYW8pCfA==
  template:
    metadata:
      name: cluster-user-auth
      namespace: flux-system
