apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wauhive.fullname" . }}-frontend
  labels:
    {{- include "wauhive.componentLabels" (merge (dict "component" "frontend") .) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "wauhive.componentSelectorLabels" (merge (dict "component" "frontend") .) | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ now | date "20060102150405" | quote }}
      labels:
        {{- include "wauhive.componentSelectorLabels" (merge (dict "component" "frontend") .) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wauhive.serviceAccountName" . }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # Next.js' default page check is a fine readiness signal.
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
