apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wauhive.fullname" . }}-data
  labels:
    {{- include "wauhive.componentLabels" (merge (dict "component" "backend") .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.backend.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
