apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vausiim
  namespace: flux-system
spec:
  releaseName: vausiim
  targetNamespace: vausiim
  interval: 30m
  chart:
    spec:
      chart: ./services/ghost
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: ghost
    externalSecrets:
      enabled: false
    namespace: vausiim
    releaseName: vausiim
    host: "vausiim.ee"

    pvc:
      storageClassName: local-path

    storage:
      active: s3
      s3:
        endpoint: "https://hel1.your-objectstorage.com"
        bucket: "vausiim"
        region: "hel1"
        forcePathStyle: true

    database:
      host: mysql.mysql.svc.cluster.local
      user: vausiim
      database: vausiim

    mail:
      enabled: true
      transport: SMTP
      from: "noreply@vausiim.ee"
      options:
        service: Mailgun
        host: smtp.eu.mailgun.org
        port: 587
        secure: false
        auth:
          user: "postmaster@mg.vausiim.ee"
