apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: waushop
  namespace: flux-system
spec:
  releaseName: web
  targetNamespace: waushop
  storageNamespace: waushop
  interval: 30m
  chart:
    spec:
      chart: ./services/waushop
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
